spring.application.name=media_db
spring.data.mongodb.uri=${MEDIA_MONGODB_URI}
server.port=8085

# Eureka Configuration
eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL:http://localhost:8761/eureka/}

# IPFS Pinata Configuration
pinata.api.key=${PINATA_API_KEY}
pinata.secret.api.key=${PINATA_SECRET_API_KEY}

# File Upload Configuration (Allow large video files up to 500MB)
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB
server.port=8085
